version: '3'

services:

  demo1-mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=demo
    ports:
      - 3306:3306

  demo1-main:
    image: demo1-main
    restart: on-failure
    depends_on:
      - demo1-mysql
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=demo1-mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=
      - DATABASE_NAME=demo
      - DATABASE_PORT=3306
